spring:
    data:
        rest:
            base-path: /api
    h2:
        :console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true